#!/usr/bin/env ruby

require 'fisherman'
require 'shellwords'
require 'fileutils'

token = ARGV[0]
album_id = ARGV[1]

Snapfish.connect(token)

STDERR.puts 'Gathering album information...'

album = Snapfish::Album.get(album_id)
album_directory =  "#{album.created_at.strftime('%Y-%m-%d')} - #{album.name}"
FileUtils.mkdir_p(album_directory)

puts "Downloading album to directory \"#{album_directory}\""
album.assets.each_with_index do |photo, index|
  file_name = index.to_s.rjust(4, '0') + '.' + photo.file_extension
  destination_file = File.join(album_directory, file_name)

  downloader = Snapfish::Downloader.new(photo)
  downloader.download(destination_file)

  if downloader.bytes > 0
    puts "Wrote #{file_name} (#{bytes.size} bytes)"
  else
    puts "Could not download photo #{photo.id}"
  end
end
