#!/usr/bin/env ruby

require 'fisherman'
require 'shellwords'

# TODO:
# - Log in using email/password
# - Use GetOpt for args

token = ARGV[0]
if token.nil?
  puts "** Usage: snapfish_albums <TOKEN>"
  exit 1
end

Snapfish.connect(token)

STDERR.puts 'Gathering album information...'

albums_json = Snapfish::AlbumCollection.new.map do |album|
  photos_json = album.assets.map(&:as_json)
  album.as_json.merge(photos: photos_json)
end

albums_json.sort_by! { |album| album[:created_at] }

if ENV['BASH_SCRIPT']
  puts <<-BASH
#!/bin/bash
#
# Downloads Snapfish albums and sorts them into folders by album title.
#
TOKEN='#{token}'

  BASH

  albums_json.each do |album_json|
    puts "download_snapfish_album $TOKEN #{album.id}"
  end
else
  puts JSON.pretty_generate(albums_json)
end
